---
- name: Copy etcd binary
  copy:
    src: "{{ BINARY_FILE_PATH }}{{ item }}"
    dest: "{{ BIN_PATH }}{{ item }}"
    owner: "{{ CURRENT_USER }}"
    group: "{{ CURRENT_USER }}"
    mode: 0755
  with_items:
   - "etcd"
   - "etcdctl" 

- name: Delete useless key.pem
  file:
    path: /etc/kubernetes/cert/{{ item }}
    state: absent
  with_items:
    - "kubernetes.pem"
    - "kubernetes-key.pem"
    - "kube-controller-manager.pem"
    - "kube-controller-manager-key.pem"
    - "kube-scheduler-key.pem"
    - "kube-scheduler.pem"
